project:
  type: website
  output-dir: docs

website:
  title: "Statisfaction - Bayes and stuff"
  site-url: https://github.com/statisfaction-blog
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/statisfaction-blog
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



