project:
  type: website
  output-dir: docs

website:
  title: "Statisfaction - I can't get no"
  site-url: https://github.com/statisfaction-blog
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/statisfaction-blog

format:
  html:
    theme: darkly
    css: styles.css

comments:
  utterances:
    repo: rbardenet/statisfaction-blog-comments
    issue-term: title
    theme: github-light

